db:
  src:
    dsn: "root:123@tcp(localhost:13316)/cblog"
  dst:
    dsn: "root:123@tcp(localhost:13316)/cblog_intr"

#migrator:
#  pattern: "SRC_ONLY"
#  web:
#    addr: ":8082"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: 8090
    etcdAddr: "localhost:12379"
    name: "interactive"