apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
        - name: internal
          image: internal:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
      volumes:
        - name: config-volume
          configMap:
            name: internal-config
