apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5.9
          ports:
            - containerPort: 2379
            - containerPort: 2380
          command:
            - etcd
            - --name=etcd0
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://etcd:2380
            - --initial-cluster=etcd0=http://etcd:2380
          volumeMounts:
            - name: data
              mountPath: /etcd-data
      volumes:
        - name: data
          emptyDir: {}