test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  dsn: "root:123@tcp(localhost:13316)/cblog"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  addrs:
    - "localhost:12379"

grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"