// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"compus_blog/basic/interactive/events"
	"compus_blog/basic/interactive/grpc"
	"compus_blog/basic/interactive/ioc"
	"compus_blog/basic/interactive/repository"
	"compus_blog/basic/interactive/repository/cache"
	"compus_blog/basic/interactive/repository/dao"
	"compus_blog/basic/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitAPP() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitSrc(loggerV1)
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGrpcxServer(loggerV1, interactiveServiceServer)
	client := ioc.InitKafka()
	interactiveReadEventBatchConsumer := events.NewInteractiveReadEventBatchConsumer(client, loggerV1, interactiveRepository)
	v := ioc.NewConsumers(interactiveReadEventBatchConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitSrc, ioc.InitLogger, ioc.InitKafka, ioc.InitSyncProducer, ioc.InitRedis)

// interactive
var interactiveSvcProvider = wire.NewSet(dao.NewInteractiveDAO, repository.NewInteractiveRepository, cache.NewInteractiveCache, service.NewInteractiveService)
